[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.0.1"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-gorp/gorp"
  version = "2.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.2.0"

[[constraint]]
  branch = "experimental"
  name = "github.com/gosexy/to"

[[constraint]]
  name = "github.com/tmilewski/goenv"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
